# Generated by Django 4.2.7 on 2023-12-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
