# Generated by Django 4.2.7 on 2024-01-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
