# Generated by Django 4.2.7 on 2024-01-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0010_userprofile_profile_picture_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_path',
        ),
    ]
