# Generated by Django 4.1.13 on 2024-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerApp', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
